services:
  - type: web
    name: deadline-countdown
    runtime: node
    rootDir: deadline-app
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
